export { default as SignInPage } from "./SignInPage";
export { default as SignUpPage } from "./SignUpPage";
export { default as MainPage } from "./MainPage";
export { default as CotegoryPage } from "./CotegoryPage";
export { default as RecommendPage } from "./RecommendPage";
export { default as ProfilePage } from "./ProfilePage";
export { default as ResultPage } from "./ResultPage";
export { default as ProblemPage } from "./ProblemPage";
export { default as NotFound } from "./NotFound";
